# Generated by Django 4.1.7 on 2023-02-20 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField(max_length=1024)),
                ('type', models.CharField(choices=[('Competition', 'Competition'), ('Show', 'Show'), ('Fundraiser', 'Fundraiser'), ('Trip', 'Trip'), ('Fair', 'Fair')], max_length=11)),
                ('location', models.CharField(max_length=64)),
                ('starts_on', models.DateTimeField()),
                ('finishes_on', models.DateTimeField()),
                ('image', models.TextField(max_length=256)),
                ('points', models.PositiveSmallIntegerField()),
                ('is_canceled', models.BooleanField(default=False)),
                ('cancellation_reason', models.TextField(blank=True, max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('content', models.TextField(max_length=16384)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rally',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_on', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_now_add=True)),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('points', models.PositiveSmallIntegerField()),
                ('grade', models.PositiveSmallIntegerField(blank=True, choices=[(5, 5), (6, 6), (7, 7), (8, 8)], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=320, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('biography', models.TextField(blank=True, max_length=280, null=True)),
                ('grade', models.PositiveSmallIntegerField(blank=True, choices=[(5, 5), (6, 6), (7, 7), (8, 8)], null=True)),
                ('image', models.TextField(default='default.jpg', max_length=256)),
                ('live_points', models.PositiveSmallIntegerField(default=0)),
                ('points', models.PositiveSmallIntegerField(default=0)),
                ('rank', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('School', 'School'), ('Food', 'Food'), ('Spirit', 'Spirit')], max_length=6)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prizes', to='core.student')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended', models.BooleanField(blank=True, null=True)),
                ('final', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='core.event')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.student')),
            ],
        ),
    ]
