# Generated by Django 4.1.7 on 2023-02-26 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(upload_to='images/events/'),
        ),
        migrations.AlterField(
            model_name='report',
            name='first_name',
            field=models.CharField(default='default first name', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='last_name',
            field=models.CharField(default='default last name', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='middle_name',
            field=models.CharField(default='default middle name', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.CharField(max_length=28, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(default='/images/students/default.jpg', null=True, upload_to='images/students/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='rank',
            field=models.PositiveSmallIntegerField(blank=True, null=True, unique=True),
        ),
    ]
