# Generated by Django 4.1.7 on 2023-02-26 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_event_image_alter_report_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='id',
            field=models.CharField(max_length=28, primary_key=True, serialize=False),
        ),
    ]
