# Generated by Django 4.1.7 on 2023-02-27 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_admin_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.CharField(max_length=36),
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.CharField(default='https://upload.wikimedia.org/wikipedia/commons/a/ac/Default_pfp.jpg', max_length=512),
        ),
    ]
