# Generated by Django 4.1.7 on 2023-06-27 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_prizeredemption_approved_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='key',
            field=models.TextField(default='A', max_length=6),
            preserve_default=False,
        ),
    ]
