# Generated by Django 4.1.7 on 2023-02-27 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_event_image_alter_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboard',
            name='created_on',
            field=models.DateField(auto_now=True),
        ),
    ]
