# Generated by Django 4.1.7 on 2023-06-27 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_group_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.CharField(max_length=1024),
        ),
    ]
