# Generated by Django 4.1.7 on 2023-02-27 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_leaderboard_created_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_canceled',
        ),
    ]
