# Generated by Django 4.1.7 on 2023-03-03 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_event_is_canceled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='last_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='middle_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
