# Generated by Django 4.1.7 on 2023-03-04 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_report_last_name_alter_report_middle_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='cancellation_reason',
            new_name='cancelation_reason',
        ),
    ]
