from .student import *
from .news import *
from .event import *
from .admin import *
from .attendance import *
from .report import *
from .leaderboard import *
from .rally import *
from .prize import *
